### ISSUE TITLE
请问rc.lua前面两行是什么意思？

### ISSUE THREAD

**Issue by lujun9972** [Trytwice/dotfiles#1]
local awesome, client, mouse, screen, tag = awesome, client, mouse, screen, tag
local ipairs, string, os, table, tostring, tonumber, type = ipairs, string, os, table, tostring, tonumber, type
这种写法是什么意思？

另外，lain这个库是干嘛的呢？

**Comment by tianhongw** [comment]
1.不懂lua,但我觉得这就是lua的定义变量和初始化, 比如 local ipairs = ipairs, 定义一个局部变量 ipairs, 初始值为 ipairs,  ipairs的类型是function, 类似 python 的 import module.ipairs as ipairs
2.lain 为 awesomewm 提供了一些布局 lain/layout、部件 lain/widget、小函数 lain/util

**Comment by lujun9972** [comment]
问题是，在awesomeWM刚启动时， awesome, client, mouse, screen, tag这些变量应该都是不存在的吧
另外，请问lain是从哪里下载的呢？

**Comment by tianhongw** [comment]
关于这点我也不清楚，https://github.com/lcpz/awesome-copycats 这个repo收集了一些 awesomewm 的配置，我用的是这个。
